NSL-KDD Testing segment -- On GitHub, the nslkdd Text File is just the KDDTrain+ text file ...

In [1]:
# Import Libraries

import pandas as pd
import numpy as np
from sklearn.preprocessing import LabelEncoder
import os
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', 100)

In [2]:
# Define file paths
DATA_DIR = "../dataset/original"  # --==-- NOTE: Upload file content manually (create dataset folder -> original folder)
TRAIN_FILE = "nslkdd.txt"      # --==-- Simply upload the nslkdd.txt file under this 2-path long directory

# Column names for the NSL-KDD dataset
column_names = [
    'duration', 'protocol_type', 'service', 'flag', 'src_bytes', 'dst_bytes',
    'land', 'wrong_fragment', 'urgent', 'hot', 'num_failed_logins', 'logged_in',
    'num_compromised', 'root_shell', 'su_attempted', 'num_root', 'num_file_creations',
    'num_shells', 'num_access_files', 'num_outbound_cmds', 'is_host_login',
    'is_guest_login', 'count', 'srv_count', 'serror_rate', 'srv_serror_rate',
    'rerror_rate', 'srv_rerror_rate', 'same_srv_rate', 'diff_srv_rate',
    'srv_diff_host_rate', 'dst_host_count', 'dst_host_srv_count',
    'dst_host_same_srv_rate', 'dst_host_diff_srv_rate', 'dst_host_same_src_port_rate',
    'dst_host_srv_diff_host_rate', 'dst_host_serror_rate', 'dst_host_srv_serror_rate',
    'dst_host_rerror_rate', 'dst_host_srv_rerror_rate', 'class', 'difficulty'
]

# Load in the dataset
train_path = os.path.join(DATA_DIR, TRAIN_FILE)
nslkdd = pd.read_csv(train_path, header=None, names=column_names)

# Displays preview of the dataset
print(f"Total instances: {nslkdd.shape[0]}")
print(f"Total Columns (41 features, 1 class label, and 1 difficulty ranking): {nslkdd.shape[1]}")
print("Preview of the first 5 instances of the NSL-KDD Dataset before processing:")
nslkdd.head()

Total instances: 125973
Total Columns (41 features, 1 class label, and 1 difficulty ranking): 43
Preview of the first 5 instances of the NSL-KDD Dataset before processing:

,duration,protocol_type,service,flag,src_bytes,dst_bytes,land,wrong_fragment,urgent,hot,num_failed_logins,logged_in,num_compromised,root_shell,su_attempted,num_root,num_file_creations,num_shells,num_access_files,num_outbound_cmds,is_host_login,is_guest_login,count,srv_count,serror_rate,srv_serror_rate,rerror_rate,srv_rerror_rate,same_srv_rate,diff_srv_rate,srv_diff_host_rate,dst_host_count,dst_host_srv_count,dst_host_same_srv_rate,dst_host_diff_srv_rate,dst_host_same_src_port_rate,dst_host_srv_diff_host_rate,dst_host_serror_rate,dst_host_srv_serror_rate,dst_host_rerror_rate,dst_host_srv_rerror_rate,class,difficulty
0,0,tcp,ftp_data,SF,491,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,2,2,0.0,0.0,0.0,0.0,1.00,0.00,0.00,150,25,0.17,0.03,0.17,0.00,0.00,0.00,0.05,0.00,normal,20
1,0,udp,other,SF,146,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,13,1,0.0,0.0,0.0,0.0,0.08,0.15,0.00,255,1,0.00,0.60,0.88,0.00,0.00,0.00,0.00,0.00,normal,15
2,0,tcp,private,S0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,123,6,1.0,1.0,0.0,0.0,0.05,0.07,0.00,255,26,0.10,0.05,0.00,0.00,1.00,1.00,0.00,0.00,neptune,19
3,0,tcp,http,SF,232,8153,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,5,5,0.2,0.2,0.0,0.0,1.00,0.00,0.00,30,255,1.00,0.00,0.03,0.04,0.03,0.01,0.00,0.01,normal,21
4,0,tcp,http,SF,199,420,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,30,32,0.0,0.0,0.0,0.0,1.00,0.00,0.09,255,255,1.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,normal,21

NOW WE HAVE WORKABLE SUBCATEGORIES FOR ENCODING

In [3]:
# Dropping difficulty column (last column)
nslkdd = nslkdd.drop('difficulty', axis=1)

print(f"Total instances: {nslkdd.shape[0]}")
print(f"Total Columns (41 features and 1 class): {nslkdd.shape[1]}")
print(f"\nPreview of the first 5 instances of the NSL-KDD Dataset after the difficulty column has been removed")
nslkdd.head()

Total instances: 125973
Total Columns (41 features and 1 class): 42

Preview of the first 5 instances of the NSL-KDD Dataset after the difficulty column has been removed

,duration,protocol_type,service,flag,src_bytes,dst_bytes,land,wrong_fragment,urgent,hot,num_failed_logins,logged_in,num_compromised,root_shell,su_attempted,num_root,num_file_creations,num_shells,num_access_files,num_outbound_cmds,is_host_login,is_guest_login,count,srv_count,serror_rate,srv_serror_rate,rerror_rate,srv_rerror_rate,same_srv_rate,diff_srv_rate,srv_diff_host_rate,dst_host_count,dst_host_srv_count,dst_host_same_srv_rate,dst_host_diff_srv_rate,dst_host_same_src_port_rate,dst_host_srv_diff_host_rate,dst_host_serror_rate,dst_host_srv_serror_rate,dst_host_rerror_rate,dst_host_srv_rerror_rate,class
0,0,tcp,ftp_data,SF,491,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,2,2,0.0,0.0,0.0,0.0,1.00,0.00,0.00,150,25,0.17,0.03,0.17,0.00,0.00,0.00,0.05,0.00,normal
1,0,udp,other,SF,146,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,13,1,0.0,0.0,0.0,0.0,0.08,0.15,0.00,255,1,0.00,0.60,0.88,0.00,0.00,0.00,0.00,0.00,normal
2,0,tcp,private,S0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,123,6,1.0,1.0,0.0,0.0,0.05,0.07,0.00,255,26,0.10,0.05,0.00,0.00,1.00,1.00,0.00,0.00,neptune
3,0,tcp,http,SF,232,8153,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,5,5,0.2,0.2,0.0,0.0,1.00,0.00,0.00,30,255,1.00,0.00,0.03,0.04,0.03,0.01,0.00,0.01,normal
4,0,tcp,http,SF,199,420,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,30,32,0.0,0.0,0.0,0.0,1.00,0.00,0.09,255,255,1.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,normal

Label encoding segment

In [4]:
# Identify and track columns containing string data types (excluding the class label)
categorical_cols = []

for col in nslkdd.columns:
    if nslkdd[col].dtype == 'str' and col != 'class':
        categorical_cols.append(col)

print(f"Categorical columns found: {categorical_cols}")
print(f"\nUnique values per column:")
for col in categorical_cols:
    print(f"  {col}: {nslkdd[col].nunique()}")
print(f"\n__________________")
# Label encode categorical columns
label_encoders = {}
encoding_mappings = {}

for col in categorical_cols:
    # Create a label encoder for this column
    le = LabelEncoder()

    # Fit and transform the column
    nslkdd[col] = le.fit_transform(nslkdd[col])

    # Preserve encoding table (to use on test set)
    label_encoders[col] = le

    # Create a mapping dictionary: original_value -> encoded_number
    encoding_mappings[col] = dict(zip(le.classes_, le.transform(le.classes_)))


# Display label mappings
for col in categorical_cols:
    print(f"{col} mappings:")
    for original, encoded in encoding_mappings[col].items():
        print(f"  {original} : {encoded}")
    print()

print(f"Preview of NSL-KDD Dataset after label encoding non-numerical features")
nslkdd.head()

Categorical columns found: []

Unique values per column:

__________________
Preview of NSL-KDD Dataset after label encoding non-numerical features

,duration,protocol_type,service,flag,src_bytes,dst_bytes,land,wrong_fragment,urgent,hot,num_failed_logins,logged_in,num_compromised,root_shell,su_attempted,num_root,num_file_creations,num_shells,num_access_files,num_outbound_cmds,is_host_login,is_guest_login,count,srv_count,serror_rate,srv_serror_rate,rerror_rate,srv_rerror_rate,same_srv_rate,diff_srv_rate,srv_diff_host_rate,dst_host_count,dst_host_srv_count,dst_host_same_srv_rate,dst_host_diff_srv_rate,dst_host_same_src_port_rate,dst_host_srv_diff_host_rate,dst_host_serror_rate,dst_host_srv_serror_rate,dst_host_rerror_rate,dst_host_srv_rerror_rate,class
0,0,tcp,ftp_data,SF,491,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,2,2,0.0,0.0,0.0,0.0,1.00,0.00,0.00,150,25,0.17,0.03,0.17,0.00,0.00,0.00,0.05,0.00,normal
1,0,udp,other,SF,146,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,13,1,0.0,0.0,0.0,0.0,0.08,0.15,0.00,255,1,0.00,0.60,0.88,0.00,0.00,0.00,0.00,0.00,normal
2,0,tcp,private,S0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,123,6,1.0,1.0,0.0,0.0,0.05,0.07,0.00,255,26,0.10,0.05,0.00,0.00,1.00,1.00,0.00,0.00,neptune
3,0,tcp,http,SF,232,8153,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,5,5,0.2,0.2,0.0,0.0,1.00,0.00,0.00,30,255,1.00,0.00,0.03,0.04,0.03,0.01,0.00,0.01,normal
4,0,tcp,http,SF,199,420,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,30,32,0.0,0.0,0.0,0.0,1.00,0.00,0.09,255,255,1.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,normal

Class Encoding Segment

In [5]:
# Encoding table
encodes = {"normal": 0,
      "back": 1, "land": 1, "neptune": 1, "pod": 1, "smurf": 1, "teardrop": 1,
      "ftp_write": 2, "guess_passwd": 2, "imap": 2, "multihop": 2, "phf": 2, "spy": 2, "warezclient": 2, "warezmaster": 2,
      "buffer_overflow": 3, "loadmodule": 3, "perl": 3, "rootkit": 3,
      "ipsweep": 4, "nmap": 4, "portsweep": 4, "satan": 4}


le_class = LabelEncoder()
nslkdd['class'] = le_class.fit_transform(nslkdd['class'])
encoding_mappings['class'] = dict(zip(le_class.classes_, le_class.transform(le_class.classes_)))


# Now, need a reverse lookup from LabelEncoder integers to original string labels
intToStrMaps = {v: k for k, v in encoding_mappings['class'].items()}


# Now, create the final mapping from LabelEncoder integers to the new categorical integers
finalRemapping = {}
for le_int_value, original_str_label in intToStrMaps.items():
    original_str_label_as_str = str(original_str_label)  # Ensure original_str_label is converted to string for comparison with 'encodes' dictionary keys
    if original_str_label_as_str in encodes:
        finalRemapping[le_int_value] = encodes[original_str_label_as_str]
    else:
        finalRemapping[le_int_value] = le_int_value


# Apply final remapping to 'class' vec
nslkdd['class'] = nslkdd['class'].map(finalRemapping).astype(np.int64)  # Change to workable integer type


print(nslkdd['class'].value_counts())

nslkdd.head()

class
0    67343
1    45927
4    11656
2      995
3       52
Name: count, dtype: int64

,duration,protocol_type,service,flag,src_bytes,dst_bytes,land,wrong_fragment,urgent,hot,num_failed_logins,logged_in,num_compromised,root_shell,su_attempted,num_root,num_file_creations,num_shells,num_access_files,num_outbound_cmds,is_host_login,is_guest_login,count,srv_count,serror_rate,srv_serror_rate,rerror_rate,srv_rerror_rate,same_srv_rate,diff_srv_rate,srv_diff_host_rate,dst_host_count,dst_host_srv_count,dst_host_same_srv_rate,dst_host_diff_srv_rate,dst_host_same_src_port_rate,dst_host_srv_diff_host_rate,dst_host_serror_rate,dst_host_srv_serror_rate,dst_host_rerror_rate,dst_host_srv_rerror_rate,class
0,0,tcp,ftp_data,SF,491,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,2,2,0.0,0.0,0.0,0.0,1.00,0.00,0.00,150,25,0.17,0.03,0.17,0.00,0.00,0.00,0.05,0.00,0
1,0,udp,other,SF,146,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,13,1,0.0,0.0,0.0,0.0,0.08,0.15,0.00,255,1,0.00,0.60,0.88,0.00,0.00,0.00,0.00,0.00,0
2,0,tcp,private,S0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,123,6,1.0,1.0,0.0,0.0,0.05,0.07,0.00,255,26,0.10,0.05,0.00,0.00,1.00,1.00,0.00,0.00,1
3,0,tcp,http,SF,232,8153,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,5,5,0.2,0.2,0.0,0.0,1.00,0.00,0.00,30,255,1.00,0.00,0.03,0.04,0.03,0.01,0.00,0.01,0
4,0,tcp,http,SF,199,420,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,30,32,0.0,0.0,0.0,0.0,1.00,0.00,0.09,255,255,1.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0

In [6]:
vectorCopy = nslkdd["class"]  # Copy of class vector to upload to the processed dataset

# Upload this modified vector to the processed dataset in below cell

print(vectorCopy)

0         0
1         0
2         1
3         0
4         0
         ..
125968    1
125969    0
125970    0
125971    1
125972    0
Name: class, Length: 125973, dtype: int64

In [17]:
nslkdd.to_csv('../dataset/processed/nslkdd_processed.txt', index = False, sep = ',', header = False)  # Writing processed DataFrame of NSLKDD to .txt file, without header

<class 'pandas.core.frame.DataFrame'>