In [89]:
# Import Libraries

import pandas as pd
import numpy as np
from sklearn.preprocessing import LabelEncoder
import os
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', 100)

In [90]:
# Define file paths
DATA_DIR = "../dataset/original"  # Relative path from preprocessing folder
TRAIN_FILE = "nslkdd.txt"

# Column names for the NSL-KDD dataset
column_names = [
    'duration', 'protocol_type', 'service', 'flag', 'src_bytes', 'dst_bytes',
    'land', 'wrong_fragment', 'urgent', 'hot', 'num_failed_logins', 'logged_in',
    'num_compromised', 'root_shell', 'su_attempted', 'num_root', 'num_file_creations',
    'num_shells', 'num_access_files', 'num_outbound_cmds', 'is_host_login',
    'is_guest_login', 'count', 'srv_count', 'serror_rate', 'srv_serror_rate',
    'rerror_rate', 'srv_rerror_rate', 'same_srv_rate', 'diff_srv_rate',
    'srv_diff_host_rate', 'dst_host_count', 'dst_host_srv_count',
    'dst_host_same_srv_rate', 'dst_host_diff_srv_rate', 'dst_host_same_src_port_rate',
    'dst_host_srv_diff_host_rate', 'dst_host_serror_rate', 'dst_host_srv_serror_rate',
    'dst_host_rerror_rate', 'dst_host_srv_rerror_rate', 'class', 'difficulty'
]

# Load in the dataset
train_path = os.path.join(DATA_DIR, TRAIN_FILE)
nslkdd = pd.read_csv(train_path, header=None, names=column_names)

# Displays preview of the dataset
print(f"Total instances: {nslkdd.shape[0]}")
print(f"Total Columns (41 features, 1 class label, and 1 difficulty ranking): {nslkdd.shape[1]}")
print("Preview of the first 5 instances of the NSL-KDD Dataset before processing:")
nslkdd.head()

Total instances: 125973
Total Columns (41 features, 1 class label, and 1 difficulty ranking): 43
Preview of the first 5 instances of the NSL-KDD Dataset before processing:

,duration,protocol_type,service,flag,src_bytes,dst_bytes,land,wrong_fragment,urgent,hot,num_failed_logins,logged_in,num_compromised,root_shell,su_attempted,num_root,num_file_creations,num_shells,num_access_files,num_outbound_cmds,is_host_login,is_guest_login,count,srv_count,serror_rate,srv_serror_rate,rerror_rate,srv_rerror_rate,same_srv_rate,diff_srv_rate,srv_diff_host_rate,dst_host_count,dst_host_srv_count,dst_host_same_srv_rate,dst_host_diff_srv_rate,dst_host_same_src_port_rate,dst_host_srv_diff_host_rate,dst_host_serror_rate,dst_host_srv_serror_rate,dst_host_rerror_rate,dst_host_srv_rerror_rate,class,difficulty
0,0,tcp,ftp_data,SF,491,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,2,2,0.0,0.0,0.0,0.0,1.00,0.00,0.00,150,25,0.17,0.03,0.17,0.00,0.00,0.00,0.05,0.00,normal,20
1,0,udp,other,SF,146,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,13,1,0.0,0.0,0.0,0.0,0.08,0.15,0.00,255,1,0.00,0.60,0.88,0.00,0.00,0.00,0.00,0.00,normal,15
2,0,tcp,private,S0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,123,6,1.0,1.0,0.0,0.0,0.05,0.07,0.00,255,26,0.10,0.05,0.00,0.00,1.00,1.00,0.00,0.00,neptune,19
3,0,tcp,http,SF,232,8153,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,5,5,0.2,0.2,0.0,0.0,1.00,0.00,0.00,30,255,1.00,0.00,0.03,0.04,0.03,0.01,0.00,0.01,normal,21
4,0,tcp,http,SF,199,420,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,30,32,0.0,0.0,0.0,0.0,1.00,0.00,0.09,255,255,1.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,normal,21

In [91]:
# Remove difficulty column (last column)
nslkdd = nslkdd.drop('difficulty', axis=1)

print(f"Total instances: {nslkdd.shape[0]}")
print(f"Total Columns (41 features and 1 class): {nslkdd.shape[1]}")
print(f"\nPreview of the first 5 instances of the NSL-KDD Dataset after the difficulty column has been removed")
nslkdd.head()

Total instances: 125973
Total Columns (41 features and 1 class): 42

Preview of the first 5 instances of the NSL-KDD Dataset after the difficulty column has been removed

,duration,protocol_type,service,flag,src_bytes,dst_bytes,land,wrong_fragment,urgent,hot,num_failed_logins,logged_in,num_compromised,root_shell,su_attempted,num_root,num_file_creations,num_shells,num_access_files,num_outbound_cmds,is_host_login,is_guest_login,count,srv_count,serror_rate,srv_serror_rate,rerror_rate,srv_rerror_rate,same_srv_rate,diff_srv_rate,srv_diff_host_rate,dst_host_count,dst_host_srv_count,dst_host_same_srv_rate,dst_host_diff_srv_rate,dst_host_same_src_port_rate,dst_host_srv_diff_host_rate,dst_host_serror_rate,dst_host_srv_serror_rate,dst_host_rerror_rate,dst_host_srv_rerror_rate,class
0,0,tcp,ftp_data,SF,491,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,2,2,0.0,0.0,0.0,0.0,1.00,0.00,0.00,150,25,0.17,0.03,0.17,0.00,0.00,0.00,0.05,0.00,normal
1,0,udp,other,SF,146,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,13,1,0.0,0.0,0.0,0.0,0.08,0.15,0.00,255,1,0.00,0.60,0.88,0.00,0.00,0.00,0.00,0.00,normal
2,0,tcp,private,S0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,123,6,1.0,1.0,0.0,0.0,0.05,0.07,0.00,255,26,0.10,0.05,0.00,0.00,1.00,1.00,0.00,0.00,neptune
3,0,tcp,http,SF,232,8153,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,5,5,0.2,0.2,0.0,0.0,1.00,0.00,0.00,30,255,1.00,0.00,0.03,0.04,0.03,0.01,0.00,0.01,normal
4,0,tcp,http,SF,199,420,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,30,32,0.0,0.0,0.0,0.0,1.00,0.00,0.09,255,255,1.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,normal

In [92]:
#TODO: Identify and Remove Zero Variance Features

# Identify columns with zero variance
zero_variance_columns = []

# Get only numeric columns
numeric_cols = nslkdd.select_dtypes(include=[np.number]).columns

# Loop through each numeric column
for col in numeric_cols:
    if nslkdd[col].var() == 0:
        zero_variance_columns.append(col)

print(f"Zero-variance columns found: {zero_variance_columns}")

# Remove those columns
if len(zero_variance_columns) > 0:
    nslkdd = nslkdd.drop(columns=zero_variance_columns)
    print(f"\nRemoved {len(zero_variance_columns)} zero-variance column(s)")
else:
    print("\nNo zero-variance columns found")

print(f"Total instances: {nslkdd.shape[0]}")
print(f"Total Columns ({nslkdd.shape[1] - 1} features and 1 class): {nslkdd.shape[1]}")
print(f"\nPreview of the first 5 instances of the NSL-KDD Dataset after removing zero-variance columns")
nslkdd.head()

Zero-variance columns found: ['num_outbound_cmds']

Removed 1 zero-variance column(s)
Total instances: 125973
Total Columns (40 features and 1 class): 41

Preview of the first 5 instances of the NSL-KDD Dataset after removing zero-variance columns

,duration,protocol_type,service,flag,src_bytes,dst_bytes,land,wrong_fragment,urgent,hot,num_failed_logins,logged_in,num_compromised,root_shell,su_attempted,num_root,num_file_creations,num_shells,num_access_files,is_host_login,is_guest_login,count,srv_count,serror_rate,srv_serror_rate,rerror_rate,srv_rerror_rate,same_srv_rate,diff_srv_rate,srv_diff_host_rate,dst_host_count,dst_host_srv_count,dst_host_same_srv_rate,dst_host_diff_srv_rate,dst_host_same_src_port_rate,dst_host_srv_diff_host_rate,dst_host_serror_rate,dst_host_srv_serror_rate,dst_host_rerror_rate,dst_host_srv_rerror_rate,class
0,0,tcp,ftp_data,SF,491,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,2,2,0.0,0.0,0.0,0.0,1.00,0.00,0.00,150,25,0.17,0.03,0.17,0.00,0.00,0.00,0.05,0.00,normal
1,0,udp,other,SF,146,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,13,1,0.0,0.0,0.0,0.0,0.08,0.15,0.00,255,1,0.00,0.60,0.88,0.00,0.00,0.00,0.00,0.00,normal
2,0,tcp,private,S0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,123,6,1.0,1.0,0.0,0.0,0.05,0.07,0.00,255,26,0.10,0.05,0.00,0.00,1.00,1.00,0.00,0.00,neptune
3,0,tcp,http,SF,232,8153,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,5,5,0.2,0.2,0.0,0.0,1.00,0.00,0.00,30,255,1.00,0.00,0.03,0.04,0.03,0.01,0.00,0.01,normal
4,0,tcp,http,SF,199,420,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,30,32,0.0,0.0,0.0,0.0,1.00,0.00,0.09,255,255,1.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,normal

In [ ]:
# Identify and track columns containing string data types (excluding the class label)
categorical_cols = []

for col in nslkdd.columns:
    if nslkdd[col].dtype == 'str' and col != 'class':
        categorical_cols.append(col)

print(f"Categorical columns found: {categorical_cols}")
print(f"\nUnique values per column:")
for col in categorical_cols:
    print(f"  {col}: {nslkdd[col].nunique()}")
print(f"\n__________________")
# Label encode categorical columns
label_encoders = {}
encoding_mappings = {}

for col in categorical_cols:
    # Create a label encoder for this column
    le = LabelEncoder()
    
    # Fit and transform the column
    nslkdd[col] = le.fit_transform(nslkdd[col])
    
    # Preserve encoding table (to use on test set)
    label_encoders[col] = le
    
    # Create a mapping dictionary: original_value -> encoded_number
    encoding_mappings[col] = dict(zip(le.classes_, le.transform(le.classes_)))


# Display label mappings
for col in categorical_cols:
    print(f"{col} mappings:")
    for original, encoded in encoding_mappings[col].items():
        print(f"  {original} : {encoded}")
    print()

print(f"Preview of NSL-KDD Dataset after label encoding non-numerical features")
nslkdd.head()

In [ ]:
#TODO: Decide on how we want to label encode the class (target) catagories

In [ ]:
#TODO: Create new text file after pre-processing (Do not overwrite original)
OUTPUT_DIR = "../dataset/processed"
OUTPUT_FILE = "nslkdd_processed.txt"

output_path = os.path.join(OUTPUT_DIR, OUTPUT_FILE)
nslkdd.to_csv(output_path, index=False)

print(f"Preprocessed data saved successfully")
print(f"File Location: {OUTPUT_DIR}")